name: Docs

on:
  push:
    branches: [master]
    paths:
      - 'docs/**'
      - 'mdoc-docs/**'
      - 'bench/results/**'
      - 'build.mill'
      - '.github/workflows/docs.yml'
      - '.github/workflows/docs-build.yml'
  workflow_dispatch:

jobs:
  docs:
    uses: ./.github/workflows/docs-build.yml
